import { defineConfig } from "astro/config";
import sitemap from "@astrojs/sitemap";
import fs from "node:fs";
import path from "node:path";

// Cloudflare Pages allows 2000 STATIC redirect rules but only 100 DYNAMIC ones (any rule
// using a splat or :placeholder). Crucially, every rule that appears *after* a dynamic
// rule is itself counted as dynamic, so the static rules must be written first or Pages
// silently drops everything past the 100th ("Skipping remaining N lines of file").
const PAGES_STATIC_LIMIT = 2000;
const REDIRECT_WARN_THRESHOLD = 1800;

// Questions are built only at /questions/<slug>. The numeric (/questions/41) and grouped
// (/questions/FOUND41) forms are 301s, so they must never appear in the sitemap either.
const questionAliasPattern = /^\/questions\/(?:\d+|[A-Za-z]+\d+)(?:\.html)?$/;

export function sitemapFilter(page) {
  const { pathname } = new URL(page);

  // Client-side redirect stub, already noindex.
  if (/^\/random(?:\.html)?$/i.test(pathname)) {
    return false;
  }

  // /q/* are redirect stubs to /questions/*.
  if (pathname.startsWith("/q/")) {
    return false;
  }

  // Slugs contain a hyphen (pc-1), aliases never do, so this cannot match a real page.
  return !questionAliasPattern.test(pathname);
}

/**
 * Emits a 301 for every legacy question URL into dist/_redirects.
 *
 * Only /questions/<slug> is built as a page, so /questions/41 and /questions/FOUND41
 * need redirects to stay alive. They are appended to the hand-written rules that Astro
 * copies from public/_redirects.
 */
function questionRedirects() {
  return {
    name: "question-redirects",
    hooks: {
      "astro:build:done": ({ dir, logger }) => {
        const generatedPath = path.resolve("./src/generated/questions.json");
        if (!fs.existsSync(generatedPath)) {
          logger.warn("src/generated/questions.json missing; no question redirects written.");
          return;
        }

        const questions = JSON.parse(fs.readFileSync(generatedPath, "utf8")).filter(
          (q) => q.published !== false
        );

        const rules = [];
        for (const question of questions) {
          const target = `/questions/${question.slug}`;
          if (typeof question.id === "number") {
            rules.push(`/questions/${question.id} ${target} 301`);
          }
          for (const code of question.groupCodes ?? []) {
            rules.push(`/questions/${code}${question.id} ${target} 301`);
          }
        }

        const outFile = path.join(fileURLToPathCompat(dir), "_redirects");

        // Hand-written rules (from public/_redirects) contain the /q/* splat, so they go
        // LAST. Anything after a splat is counted against the 100-rule dynamic limit.
        const handWritten = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf8").trim() : "";
        const body = [
          "# Generated by the question-redirects integration in astro.config.mjs.",
          "# Legacy numeric and grouped question URLs; the slug form is the built page.",
          "# These are static rules and MUST stay above any splat/placeholder rule.",
          ...rules,
          "",
          handWritten,
          "",
        ].join("\n");

        fs.writeFileSync(outFile, body);

        const isRule = (l) => l.trim() && !l.trim().startsWith("#");
        const isDynamic = (l) => /[*:]/.test(l.split(/\s+/)[0] ?? "");
        const allRules = body.split("\n").filter(isRule);
        const firstDynamic = allRules.findIndex(isDynamic);
        const staticCount = firstDynamic === -1 ? allRules.length : firstDynamic;
        const dynamicCount = allRules.length - staticCount;

        logger.info(
          `wrote ${rules.length} question redirects (${staticCount} static, ${dynamicCount} dynamic)`
        );

        if (dynamicCount > 100) {
          logger.warn(
            `${dynamicCount} dynamic redirect rules; Cloudflare Pages only honours 100 and ` +
              `silently drops the rest. Static rules must come first in _redirects.`
          );
        }
        if (staticCount > REDIRECT_WARN_THRESHOLD) {
          logger.warn(
            `${staticCount} static redirect rules; Cloudflare Pages allows ${PAGES_STATIC_LIMIT}. ` +
              `Roughly ${Math.floor((PAGES_STATIC_LIMIT - staticCount) / 2)} more questions will fit.`
          );
        }
      },
    },
  };
}

// The build:done hook receives dir as a URL.
function fileURLToPathCompat(dir) {
  return typeof dir === "string" ? dir : new URL(dir).pathname.replace(/^\/([A-Za-z]:)/, "$1");
}

export default defineConfig({
  site: "https://usa.catechize.ing",
  build: {
    format: "file",
  },
  integrations: [sitemap({ filter: sitemapFilter }), questionRedirects()],
  vite: {
    resolve: {
      alias: {
        "@": path.resolve("./src"),
      },
    },
  },
});
